### ISSUE TITLE
intake issues with opening authorised catalogue resolved!

### ISSUE THREAD

**Issue by AliciaTak** [ACDguide/BigData#33]
intake had issues with opening an authorised thredds catalogue. Including the username and password in the URL helped to open the catalogue but passing data to dask generated an error message relating to "nonnumeric port" in the URL. Nikhil from CSIRO Data61 advised me to create a .netrc file and a .dodsrc file in my home directory to resolve the issue. The .netrc file contains details about the machine, username, and password. The .dodsrc file points to the location of the .netrc file. I work on OOD and it wasn't enough to create these files in my NCI home directory, I had to create them in my OOD home directory to resolve the issue.

**Comment by AliciaTak** [comment]
I added a section to "accessing_data" content. Feel free to edit it :)

**Comment by paigem** [comment]
Thanks for adding this to our guide @AliciaTak! 

Do you think it would be helpful to provide (or provide a link to) example .netrc and .dodsrc files? I see that you linked to info on how to write a .netrc file, but an example script might be helpful as well?

**Comment by AliciaTak** [comment]
No worries. The files contain a single line each, I added these lines to the content and committed the changes.

**Comment by AliciaTak** [comment]
![image](https://user-images.githubusercontent.com/39112008/149056794-88ebd12c-e9da-4cd3-b1b8-f7e26957675e.png)
Committing changes caused this error, can you see the changes anyways?

**Comment by paigem** [comment]
Hmm... I'm not sure what that error means. Looks like there was an error with the rebuilding of the book.

I can still view the Jupyter Book fine, but I don't see your most recent update. I'll look into this now and see if I figure anything out!

**Comment by AliciaTak** [comment]
I did another commit, I think it worked now.

**Comment by paigem** [comment]
Hooray! I love when trying something again fixes a problem! 😄 Thanks for this!

Also, we decided it's probably best to create pull requests when updating anything in the book (other than minor typos). So next time maybe try to create a PR instead of committing directly to the main branch.

**Comment by AliciaTak** [comment]
Yes, will do!
Do you know why only some words between <> do not appear in the book, e.g. <password> and <YourHomeDirectory>? Any solutions for these two?
![image](https://user-images.githubusercontent.com/39112008/149061233-5a05e8c7-d004-43e8-89de-28a0069550c4.png)
![image](https://user-images.githubusercontent.com/39112008/149061432-5e4e0397-e1cc-4b57-8f33-387ec6f0d03a.png)

**Comment by paigem** [comment]
Looking at the book right now, it looks everything between angled brackets seems to be appearing just fine (unless there is more that I didn't realize I was missing!). Maybe the new build hadn't quite finished when you first looked? 

Screenshot:
![image](https://user-images.githubusercontent.com/26591824/149061858-7bec284d-411d-4671-9cec-5e466de19642.png)

**Comment by paigem** [comment]
Also, this is super picky, but I think it might be slightly clearer to add some wording that the text in brackets is all that is needed to write those files. 

E.g. "The .netrc file contains details about the machine, username, and password and is a single-line file that can written in the following format: machine <machine_name> login <user_ID> password <password>."

And then include something similar for the .netrc file. Happy to make this edit if it's any trouble for you! (Also, no need to start a PR since this is just a small wording adjustment.)

**Comment by AliciaTak** [comment]
Yeah, I actually deleted the comment about the <> after sending it, as you said it just needed time :)

Clarity is good and not too picky, I'll add the suggested :) Thanks!

**Comment by hot007** [comment]
Another minor one, in the green callout at the bottom of the page, 
"For dataset users: if an intake catalog is already set up on your system, then all you need to know if the code to access the dataset you are interested in!"
That second clause should be "all you need to know _is_ the code" not _if_.
Otherwise looks good to me :)
